name: Test and deploy docker container

# Trigger the workflow only for the master branch.
on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow.
env:
  IMAGE_TAG: ${{ github.repository_owner }}/webrender

jobs:
  setup-build-publish-deploy:
    name: Test the code, build the container, publish and deploy to the cluster
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build & test
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run build
    - run: npm run test

    # Build & push the container
    - name: Build container image
      run: |
        docker build \
        -t ${{ env.IMAGE_TAG }} \
        .
    - run: docker push ${{ env.IMAGE_TAG }}
