name: build & test

# Trigger the workflow only for the master branch.
on:
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow.
env:
  IMAGE_TAG: ${{ secrets.DOCKERHUB_USER }}/webrender

jobs:
  build-test-deploy:
    name: Build, test and publish
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build & test
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run build
    - run: npm run test

    - name: Get package version
      id: package-version
      uses: koj-co/package-version-action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Build & push the container
    - name: Build container image
      run: |
        docker build \
        -t ${{ env.IMAGE_TAG }}:latest \
        -t ${{ env.IMAGE_TAG }}:${{ steps.package-version.outputs.package-version }} \
        .
    - name: Validate docker container before pushing
      run: |
        docker-compose -f docker-compose.yaml up -d
        sleep 5
        curl -v --fail http://localhost:8080/health-check/
    - run: docker push --all-tags ${{ env.IMAGE_TAG }}
