name: build & test

# Trigger the workflow only for the master branch.
on:
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow.
env:
  IMAGE_TAG: ${{ secrets.DOCKERHUB_USER }}/webrender

jobs:
  build-test-deploy:
    name: Build, test and publish
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build & test
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run build
    - run: npm run test

    # Build & push the container
    - name: Build container image
      run: |
        docker build \
        -t ${{ env.IMAGE_TAG }} \
        .
    - run: docker push ${{ env.IMAGE_TAG }}
